import * as pdfjs from './vendor/pdf.min.mjs';
pdfjs.GlobalWorkerOptions.workerSrc='./vendor/pdf.worker.min.mjs';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={photos:[],drawings:[],orientation:'landscape',view:'photos',drawingId:null,tool:'select',selected:null,zoom:1,dzoom:1};
let timer,dragId,pointer=null,preview=null,pdfJobs=Promise.resolve();
const uid=()=>crypto.randomUUID(),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
$('#date').value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);
function toast(s){$('#status').textContent=s;$('#status').style.display='block';clearTimeout(timer);timer=setTimeout(()=>$('#status').style.display='none',4500)}
async function busy(s,fn){$('#busy').hidden=false;$('#busy-text').textContent=s;await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));try{return await fn()}catch(e){console.error(e);toast(e.message||'処理できませんでした。別のファイルでお試しください。')}finally{$('#busy').hidden=true}}
function currentDrawing(){return state.drawings.find(d=>d.id===state.drawingId)}
function meta(){return{title:$('#title').value.trim()||'工事指示書',project:$('#project').value,date:$('#date').value}}
function movePhoto(id,before){const from=state.photos.findIndex(p=>p.id===id),to=state.photos.findIndex(p=>p.id===before);if(from<0||to<0||from===to)return;state.photos.splice(to,0,state.photos.splice(from,1)[0]);render();}
// Paper and sidebar share the same photo IDs, comments and drop behavior.
function clearPhotoDrag(){document.querySelectorAll('.photo-drop-target,.photo-dragging').forEach(el=>el.classList.remove('photo-drop-target','photo-dragging'));dragId=null}
function photoDropTarget(node){return node?.closest?.('.drawing-stage,.photo-cell,.thumb')||null}
function highlightPhotoDrop(target){document.querySelectorAll('.photo-drop-target').forEach(el=>el.classList.remove('photo-drop-target'));if(target)target.classList.add('photo-drop-target')}
function addPhotoNumber(photoId,clientX,clientY,stage){const d=currentDrawing();if(!d||!state.photos.some(p=>p.id===photoId))return;const rect=stage.getBoundingClientRect();const a={id:uid(),type:'number',photoId,x:Math.max(0,Math.min(d.w,(clientX-rect.left)*d.w/rect.width)),y:Math.max(0,Math.min(d.h,(clientY-rect.top)*d.h/rect.height)),color:$('#color').value,stroke:Number($('#stroke').value)};d.annotations.push(a);state.selected=a.id;snapshot(d);renderAnnotations();toast('写真 '+(state.photos.findIndex(p=>p.id===photoId)+1)+' の番号を配置しました。')}
function dropPhoto(photoId,target,x,y){if(!target||!state.photos.some(p=>p.id===photoId))return;if(target.classList.contains('drawing-stage')){addPhotoNumber(photoId,x,y,target);return}const other=target.dataset.photoId||target.dataset.id;if(other){movePhoto(photoId,other);return}if(target.dataset.slotIndex!==undefined){const from=state.photos.findIndex(p=>p.id===photoId);const to=Math.min(Number(target.dataset.slotIndex),state.photos.length-1);if(from!==to){state.photos.splice(to,0,state.photos.splice(from,1)[0]);render()}}}
function bindPhotoDrop(el){el.addEventListener('dragover',e=>{if(!dragId)return;e.preventDefault();e.stopPropagation();e.dataTransfer.dropEffect='move';highlightPhotoDrop(el)});el.addEventListener('dragleave',e=>{if(!el.contains(e.relatedTarget))el.classList.remove('photo-drop-target')});el.addEventListener('drop',e=>{const id=e.dataTransfer.getData('application/x-snapshot-photo')||dragId;if(!id)return;e.preventDefault();e.stopPropagation();dropPhoto(id,el,e.clientX,e.clientY);clearPhotoDrag()})}
function bindPhotoDrag(handle,photo,visual){handle.draggable=true;handle.querySelectorAll('img').forEach(img=>img.draggable=false);handle.addEventListener('dragstart',e=>{if(e.target.closest('button,textarea')){e.preventDefault();return}dragId=photo.id;e.dataTransfer.setData('application/x-snapshot-photo',photo.id);e.dataTransfer.setData('text/plain',photo.id);e.dataTransfer.effectAllowed='move';visual.classList.add('photo-dragging')});handle.addEventListener('dragend',clearPhotoDrag);if(visual.classList.contains('thumb'))bindPhotoDrop(visual);const touchHandle=visual.classList.contains('thumb')?handle.querySelector('img'):handle;touchHandle.style.touchAction='none';let touch=null;touchHandle.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'||e.target.closest('button,textarea'))return;e.preventDefault();touchHandle.setPointerCapture(e.pointerId);dragId=photo.id;const ghost=document.createElement('div');ghost.className='photo-drag-ghost';ghost.innerHTML='<img src="'+photo.src+'" alt=""><span>'+ (state.photos.findIndex(p=>p.id===photo.id)+1)+'</span>';document.body.append(ghost);ghost.style.left=e.clientX+'px';ghost.style.top=e.clientY+'px';touch={ghost};visual.classList.add('photo-dragging')});touchHandle.addEventListener('pointermove',e=>{if(!touch)return;touch.ghost.style.left=e.clientX+'px';touch.ghost.style.top=e.clientY+'px';highlightPhotoDrop(photoDropTarget(document.elementFromPoint(e.clientX,e.clientY)));if(e.clientY>window.innerHeight-45)window.scrollBy(0,18);else if(e.clientY<45)window.scrollBy(0,-18)});touchHandle.addEventListener('pointerup',e=>{if(!touch)return;const target=photoDropTarget(document.elementFromPoint(e.clientX,e.clientY));touch.ghost.remove();touch=null;dropPhoto(photo.id,target,e.clientX,e.clientY);clearPhotoDrag()});touchHandle.addEventListener('pointercancel',()=>{if(touch){touch.ghost.remove();touch=null;clearPhotoDrag()}})}
async function addPhotos(files){const images=[...files].filter(f=>f.type.startsWith('image/'));if(!images.length){toast('JPG・PNGなどの写真を選んでください。');return}await busy('写真を読み込んでいます…',async()=>{let errors=0;for(const f of images){try{const url=URL.createObjectURL(f),im=new Image();im.src=url;try{await im.decode()}finally{URL.revokeObjectURL(url)}const ratio=Math.min(1,1600/Math.max(im.naturalWidth,im.naturalHeight));const c=document.createElement('canvas');c.width=Math.round(im.naturalWidth*ratio);c.height=Math.round(im.naturalHeight*ratio);c.getContext('2d').drawImage(im,0,0,c.width,c.height);const src=c.toDataURL('image/jpeg',.9),img=new Image();img.src=src;await img.decode();state.photos.push({id:uid(),name:f.name,src,img,w:c.width,h:c.height,comment:''})}catch{errors++}}render();toast(errors?`${images.length-errors}枚追加しました。${errors}枚は読み込めませんでした。HEICはJPGに変換してください。`:`${images.length}枚の写真を追加しました。`)});}
$('#photos-input').onchange=e=>{addPhotos(e.target.files);e.target.value=''};const upload=$('.upload');upload.ondragover=e=>{e.preventDefault();upload.classList.add('dragover')};upload.ondragleave=()=>upload.classList.remove('dragover');upload.ondrop=e=>{e.preventDefault();upload.classList.remove('dragover');addPhotos(e.dataTransfer.files)};
function render(){renderPhotos();renderPapers();renderDrawingList();renderNumbers();if(state.view==='drawing')renderDrawing();updateButtons()}
function updateButtons(){const any=state.photos.length||state.drawings.length;['#print','#pdf-export','#excel-export'].forEach(s=>$(s).disabled=!any);$('#photo-count').textContent=state.photos.length;$('#drawing-count').textContent=state.drawings.length;const n=Math.ceil(state.photos.length/(state.orientation==='landscape'?4:3));$('#summary').textContent=any?`${state.photos.length}枚の写真 / 台帳${n}ページ / 図面${state.drawings.length}ページ`:'写真を追加して始めましょう'}
function renderPhotos(){const el=$('#photo-list');el.replaceChildren();state.photos.forEach((p,i)=>{const card=document.createElement('div');card.className='thumb';card.draggable=true;card.dataset.id=p.id;card.innerHTML=`<div class="thumb-number">${i+1}</div><img src="${p.src}" alt="写真 ${i+1}"><div><div class="thumb-name" title="${esc(p.name)}">${esc(p.name)}</div><div class="thumb-actions"><button data-action="up" aria-label="写真${i+1}を前へ">↑</button><button data-action="down" aria-label="写真${i+1}を後へ">↓</button><button data-action="remove" aria-label="写真${i+1}を削除">×</button></div></div>`;card.querySelectorAll('button').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='remove'){state.photos=state.photos.filter(x=>x.id!==p.id);state.drawings.forEach(d=>{d.annotations=d.annotations.filter(a=>a.photoId!==p.id);d.history=d.history.map(h=>h.filter(a=>a.photoId!==p.id))});render()}else{const j=i+(a==='up'?-1:1);if(j>=0&&j<state.photos.length)movePhoto(p.id,state.photos[j].id)}});bindPhotoDrag(card,p,card);el.append(card)})}
function renderPapers(){const root=$('#papers');root.replaceChildren();if(!state.photos.length){root.innerHTML='<div class="empty"><span>▣</span><h2>写真から、伝わる指示書へ。</h2><p>数十枚まとめて追加できます。<br>横A4は4枚、縦A4は3枚ずつ自動で配置します。</p><label class="primary inline-upload">写真を選ぶ<input type="file" accept="image/*" multiple></label></div>';root.querySelector('input').onchange=e=>addPhotos(e.target.files);return}const count=state.orientation==='landscape'?4:3,total=Math.ceil(state.photos.length/count),m=meta();for(let page=0;page<total;page++){const wrap=document.createElement('div');wrap.className='paper-wrap';wrap.style.width=`${state.zoom*100}%`;wrap.innerHTML=`<div class="paper-meta"><span>${state.orientation==='landscape'?'A4 横 / 写真4枚':'A4 縦 / 写真3枚'}</span><span>${page+1} / ${total} ページ</span></div><div class="paper ${state.orientation}"><div class="paper-title"><span>${esc(m.title)}</span><small>${esc(m.date)}</small></div><div class="paper-sub"><span>${esc(m.project)||'工事名・場所'}</span><span>写真 ${page*count+1}–${Math.min((page+1)*count,state.photos.length)}</span></div><div class="photo-grid"></div><div class="paper-footer"><span>スナップショット</span><span>${page+1} / ${total}</span></div></div>`;const grid=wrap.querySelector('.photo-grid');for(let j=0;j<count;j++){const p=state.photos[page*count+j],cell=document.createElement('div');cell.className='photo-cell';if(p){cell.innerHTML=`<div class="image-box"><span class="badge">${page*count+j+1}</span><img src="${p.src}" alt="写真${page*count+j+1}"></div><textarea class="comment" aria-label="写真${page*count+j+1}のコメント" placeholder="指示内容・コメントを入力">${esc(p.comment)}</textarea>`;cell.dataset.photoId=p.id;bindPhotoDrag(cell.querySelector('.image-box'),p,cell);cell.querySelector('textarea').oninput=e=>{p.comment=e.target.value}}else cell.innerHTML='<div class="image-box"></div><div class="comment"></div>';cell.dataset.slotIndex=page*count+j;bindPhotoDrop(cell);grid.append(cell)}root.append(wrap)}}
['#title','#project','#date'].forEach(s=>$(s).oninput=renderPapers);$$('[data-orientation]').forEach(b=>b.onclick=()=>{state.orientation=b.dataset.orientation;$$('[data-orientation]').forEach(x=>x.classList.toggle('active',x===b));renderPapers();updateButtons()});
function switchView(v){state.view=v;$('#photo-workspace').hidden=v!=='photos';$('#drawing-workspace').hidden=v!=='drawing';$('#tab-photos').classList.toggle('active',v==='photos');$('#tab-drawing').classList.toggle('active',v==='drawing');if(v==='drawing')renderDrawing()}
$('#tab-photos').onclick=()=>switchView('photos');$('#tab-drawing').onclick=()=>switchView('drawing');$('#zoom-in').onclick=()=>{state.zoom=Math.min(2,state.zoom+.1);$('#zoom-label').textContent=Math.round(state.zoom*100)+'%';renderPapers()};$('#zoom-out').onclick=()=>{state.zoom=Math.max(.5,state.zoom-.1);$('#zoom-label').textContent=Math.round(state.zoom*100)+'%';renderPapers()};
async function addPDF(files){const f=[...files];await busy('図面PDFを読み込んでいます…',async()=>{for(const file of f){if(!/\.pdf$/i.test(file.name)&&file.type!=='application/pdf')continue;let doc;try{doc=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer()),cMapUrl:"./vendor/cmaps/",cMapPacked:true,standardFontDataUrl:"./vendor/standard_fonts/"}).promise;for(let i=1;i<=doc.numPages;i++){const page=await doc.getPage(i);const base=page.getViewport({scale:1}),scale=Math.min(2,2200/Math.max(base.width,base.height));const vp=page.getViewport({scale}),canvas=document.createElement('canvas');canvas.width=Math.round(vp.width);canvas.height=Math.round(vp.height);await page.render({canvasContext:canvas.getContext('2d'),viewport:vp}).promise;const d={id:uid(),name:file.name,page:i,canvas,w:canvas.width,h:canvas.height,annotations:[],history:[[]],hi:0};state.drawings.push(d);if(!state.drawingId)state.drawingId=d.id;page.cleanup()}}finally{if(doc)await doc.destroy()}}render();switchView('drawing');toast('図面を追加しました。写真番号を選んで配置できます。')})}
['#pdf-input','#pdf-input-empty'].forEach(s=>$(s).onchange=e=>{const files=[...e.target.files];pdfJobs=pdfJobs.then(()=>addPDF(files));e.target.value=''});
function renderDrawingList(){const list=$('#drawing-list');list.replaceChildren();state.drawings.forEach(d=>{const row=document.createElement('div');row.className='drawing-item';const name=document.createElement('span');name.textContent=`${d.name} · ${d.page}ページ`;name.title=name.textContent;const open=document.createElement('button');open.textContent='開く';open.onclick=()=>{state.drawingId=d.id;state.selected=null;switchView('drawing');renderDrawingList()};const remove=document.createElement('button');remove.textContent='×';remove.setAttribute('aria-label','図面を削除');remove.onclick=()=>{state.drawings=state.drawings.filter(x=>x!==d);if(state.drawingId===d.id)state.drawingId=state.drawings[0]?.id||null;state.selected=null;render()};row.append(name,open,remove);list.append(row)});const s=$('#drawing-select');s.replaceChildren();state.drawings.forEach(d=>{const o=new Option(`${d.name} / ${d.page}ページ`,d.id);s.add(o)});s.value=state.drawingId||''}
$('#drawing-select').onchange=e=>{state.drawingId=e.target.value;state.selected=null;renderDrawing()};
function renderNumbers(){const s=$('#number-select'),old=s.value;s.replaceChildren();state.photos.forEach((p,i)=>s.add(new Option(`${i+1} · ${p.name}`,p.id)));if(state.photos.some(p=>p.id===old))s.value=old}
const toolHints={select:'配置した番号や注記を選択して移動できます。',number:'左の写真を図面へドラッグ、または番号を選んでクリックして配置します。',marker:'図面上をドラッグしてマーカーを引きます。',arrow:'図面上をドラッグして矢印を描きます。',rect:'図面上をドラッグして四角で囲みます。',circle:'図面上をドラッグして丸で囲みます。',text:'文字を入力し、図面上をクリックして配置します。',symbol:'記号を選び、図面上をクリックして配置します。'};
$$('[data-tool]').forEach(b=>b.onclick=()=>{state.tool=b.dataset.tool;state.selected=null;$$('[data-tool]').forEach(x=>x.classList.toggle('active',x===b));$('#number-option').hidden=state.tool!=='number';$('#text-option').hidden=state.tool!=='text';$('#symbol-option').hidden=state.tool!=='symbol';$('#tool-hint').textContent=toolHints[state.tool];renderAnnotations()});
function snapshot(d){d.history=d.history.slice(0,d.hi+1);d.history.push(structuredClone(d.annotations));if(d.history.length>100)d.history.shift();d.hi=d.history.length-1;updateUndo()}
function updateUndo(){const d=currentDrawing();$('#undo').disabled=!d||!d.hi;$('#redo').disabled=!d||d.hi>=d.history.length-1;$('#delete-annotation').disabled=!d||!state.selected;$('#rotate-left').disabled=!d;$('#rotate-right').disabled=!d}
function undo(dir){const d=currentDrawing();if(!d||d.hi+dir<0||d.hi+dir>=d.history.length)return;d.hi+=dir;d.annotations=structuredClone(d.history[d.hi]);state.selected=null;renderAnnotations()}
$('#undo').onclick=()=>undo(-1);$('#redo').onclick=()=>undo(1);$('#delete-annotation').onclick=()=>{const d=currentDrawing();if(d&&state.selected){d.annotations=d.annotations.filter(a=>a.id!==state.selected);state.selected=null;snapshot(d);renderAnnotations()}};
document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(state.view==='drawing'&&(e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo(e.shiftKey?1:-1)}if(state.view==='drawing'&&(e.key==='Delete'||e.key==='Backspace')){$('#delete-annotation').click();e.preventDefault()}});
function renderDrawing(){const d=currentDrawing(),container=$('#drawing-container');if(!d){container.innerHTML='<div class="empty"><span>▧</span><h2>図面PDFを追加してください</h2><p>左側の「図面PDFを追加」から追加できます。写真のみでも印刷・ダウンロードできます。</p></div>';updateUndo();return}container.replaceChildren();const stage=document.createElement('div');stage.className='drawing-stage';const base=Math.max(280,container.clientWidth-48);stage.style.width=base*state.dzoom+'px';stage.style.aspectRatio=d.w+'/'+d.h;const c=document.createElement('canvas');c.width=d.w;c.height=d.h;c.getContext('2d').drawImage(d.canvas,0,0);const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox',`0 0 ${d.w} ${d.h}`);svg.setAttribute('aria-label','図面編集エリア');stage.append(c,svg);container.append(stage);bindPhotoDrop(stage);svg.addEventListener('pointerdown',startDraw);svg.addEventListener('pointermove',moveDraw);svg.addEventListener('pointerup',endDraw);svg.addEventListener('pointercancel',cancelDraw);renderAnnotations()}
function rotateAnnotation(a,w,h,clockwise){const rotate=(x,y)=>clockwise?[h-y,x]:[y,w-x];const b=structuredClone(a);[b.x,b.y]=rotate(a.x,a.y);if(a.x2!==undefined)[b.x2,b.y2]=rotate(a.x2,a.y2);if(a.points)b.points=a.points.map(([x,y])=>rotate(x,y));return b}
function rotateDrawing(clockwise){const d=currentDrawing();if(!d)return;const w=d.w,h=d.h,c=document.createElement('canvas');c.width=h;c.height=w;const ctx=c.getContext('2d');if(clockwise){ctx.translate(h,0);ctx.rotate(Math.PI/2)}else{ctx.translate(0,w);ctx.rotate(-Math.PI/2)}ctx.drawImage(d.canvas,0,0);d.canvas=c;d.w=h;d.h=w;d.annotations=d.annotations.map(a=>rotateAnnotation(a,w,h,clockwise));d.history=d.history.map(items=>items.map(a=>rotateAnnotation(a,w,h,clockwise)));pointer=null;preview=null;renderDrawing();toast(clockwise?'図面を右に90度回転しました。':'図面を左に90度回転しました。')}
$('#rotate-left').onclick=()=>rotateDrawing(false);$('#rotate-right').onclick=()=>rotateDrawing(true);
['in','out'].forEach(dir=>$('#drawing-zoom-'+dir).onclick=()=>{state.dzoom=Math.max(.4,Math.min(3,state.dzoom+(dir==='in'?.2:-.2)));$('#drawing-zoom-label').textContent=Math.round(state.dzoom*100)+'%';renderDrawing()});
function svgAnnotation(a,d,selected=false){const color=a.color,sz=Math.max(d.w,d.h)*.024,sw=a.stroke* Math.max(d.w,d.h)/1400,x=Math.min(a.x,a.x2??a.x),y=Math.min(a.y,a.y2??a.y),w=Math.abs((a.x2??a.x)-a.x),h=Math.abs((a.y2??a.y)-a.y),attr=`data-id="${a.id}" class="annotation${selected?' selected':''}"`;if(a.type==='number'){const n=state.photos.findIndex(p=>p.id===a.photoId)+1;if(!n)return '';return `<g ${attr}><circle cx="${a.x}" cy="${a.y}" r="${sz*.8}" fill="white" stroke="${color}" stroke-width="${sw}"/><text x="${a.x}" y="${a.y+sz*.34}" font-family="sans-serif" font-weight="bold" text-anchor="middle" font-size="${sz}" fill="${color}">${n}</text></g>`}if(a.type==='text'||a.type==='symbol')return `<text ${attr} x="${a.x}" y="${a.y}" fill="${color}" font-family="sans-serif" font-size="${sz}" font-weight="bold">${esc(a.text)}</text>`;if(a.type==='rect')return `<rect ${attr} x="${x}" y="${y}" width="${w}" height="${h}" fill="transparent" stroke="${color}" stroke-width="${sw}"/>`;if(a.type==='circle')return `<ellipse ${attr} cx="${x+w/2}" cy="${y+h/2}" rx="${w/2}" ry="${h/2}" fill="transparent" stroke="${color}" stroke-width="${sw}"/>`;if(a.type==='arrow'){const angle=Math.atan2(a.y2-a.y,a.x2-a.x),len=sz;return `<g ${attr} stroke="${color}" stroke-width="${sw}" fill="none"><path d="M${a.x} ${a.y}L${a.x2} ${a.y2}M${a.x2-len*Math.cos(angle-.5)} ${a.y2-len*Math.sin(angle-.5)}L${a.x2} ${a.y2}L${a.x2-len*Math.cos(angle+.5)} ${a.y2-len*Math.sin(angle+.5)}"/></g>`}return `<polyline ${attr} points="${a.points.map(p=>p.join(',')).join(' ')}" fill="none" stroke="${color}" stroke-width="${sw*5}" opacity=".32" stroke-linecap="round" stroke-linejoin="round"/>`}
function renderAnnotations(){const d=currentDrawing(),svg=$('.drawing-stage svg');if(d&&svg)svg.innerHTML=d.annotations.concat(preview?[preview]:[]).map(a=>svgAnnotation(a,d,a.id===state.selected)).join('');updateUndo()}
function point(e){const d=currentDrawing(),r=e.currentTarget.getBoundingClientRect();return{x:Math.max(0,Math.min(d.w,(e.clientX-r.left)*d.w/r.width)),y:Math.max(0,Math.min(d.h,(e.clientY-r.top)*d.h/r.height))}}
function startDraw(e){if(e.button!==0)return;const d=currentDrawing(),p=point(e);e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);if(state.tool==='select'){const id=e.target.closest('[data-id]')?.dataset.id;state.selected=id||null;pointer=id?{start:p,original:structuredClone(d.annotations.find(a=>a.id===id)),changed:false}:null;renderAnnotations();return}const a={id:uid(),type:state.tool,...p,color:$('#color').value,stroke:Number($('#stroke').value)};if(a.type==='number'){a.photoId=$('#number-select').value;if(!a.photoId){toast('先に写真を追加してください。');return}}if(a.type==='text'||a.type==='symbol'){a.text=a.type==='text'?$('#annotation-text').value:$('#symbol-select').value;if(!a.text.trim()){toast('配置する文字を入力してください。');return}}if(['number','text','symbol'].includes(a.type)){d.annotations.push(a);snapshot(d);renderAnnotations();return}a.x2=p.x;a.y2=p.y;if(a.type==='marker')a.points=[[p.x,p.y]];preview=a;pointer={start:p};renderAnnotations()}
function moveDraw(e){if(!pointer)return;const d=currentDrawing(),p=point(e);if(state.tool==='select'&&pointer.original){const original=pointer.original,dx=p.x-pointer.start.x,dy=p.y-pointer.start.y,a=d.annotations.find(a=>a.id===original.id);a.x=original.x+dx;a.y=original.y+dy;if(original.x2!==undefined){a.x2=original.x2+dx;a.y2=original.y2+dy}if(original.points)a.points=original.points.map(([x,y])=>[x+dx,y+dy]);pointer.changed=true}else if(preview){preview.x2=p.x;preview.y2=p.y;if(preview.type==='marker')preview.points.push([p.x,p.y])}renderAnnotations()}
function endDraw(){const d=currentDrawing();if(preview){if(Math.hypot(preview.x2-preview.x,preview.y2-preview.y)>3||preview.type==='marker'&&preview.points.length>1){d.annotations.push(preview);snapshot(d)}preview=null}else if(pointer?.changed)snapshot(d);pointer=null;renderAnnotations()}
function cancelDraw(){const d=currentDrawing();if(pointer?.original){const i=d.annotations.findIndex(a=>a.id===pointer.original.id);d.annotations[i]=pointer.original}pointer=null;preview=null;renderAnnotations()}
// Canvas output uses the same photo sequence and annotations as the editor.
function fitImage(ctx,img,x,y,w,h){const r=Math.min(w/img.width,h/img.height);ctx.drawImage(img,x+(w-img.width*r)/2,y+(h-img.height*r)/2,img.width*r,img.height*r)}
function wrappedText(ctx,text,x,y,maxWidth,lineHeight,maxLines){let lines=[],line='';for(const ch of String(text)){if(ch==='\n'){lines.push(line);line='';continue}if(ctx.measureText(line+ch).width>maxWidth&&line){lines.push(line);line=ch}else line+=ch}lines.push(line);lines.slice(0,maxLines).forEach((l,i)=>ctx.fillText(l,x,y+i*lineHeight));if(lines.length>maxLines)toast('長いコメントの一部は紙面に収まりません。コメントを短くしてください。')}
function photoPages(){const count=state.orientation==='landscape'?4:3,total=Math.ceil(state.photos.length/count),m=meta(),result=[];for(let page=0;page<total;page++){const c=document.createElement('canvas'),land=state.orientation==='landscape';c.width=land?1684:1190;c.height=land?1190:1684;const g=c.getContext('2d'),margin=land?70:60,W=c.width-2*margin;g.fillStyle='white';g.fillRect(0,0,c.width,c.height);g.fillStyle='#21373d';g.font='bold 32px sans-serif';g.fillText(m.title,margin,margin+32,W-240);g.font='20px sans-serif';g.textAlign='right';g.fillText(m.date,c.width-margin,margin+32);g.textAlign='left';g.fillStyle='#28454e';g.fillRect(margin,margin+49,W,3);g.fillStyle='#5d737a';g.font='20px sans-serif';g.fillText(m.project,margin,margin+85,W-220);g.textAlign='right';g.fillText(`写真 ${page*count+1}–${Math.min((page+1)*count,state.photos.length)}`,c.width-margin,margin+85);g.textAlign='left';const top=margin+115,bottom=c.height-margin-35,gap=26,cw=land?(W-gap)/2:W,ch=land?(bottom-top-gap)/2:(bottom-top-gap*2)/3;for(let j=0;j<count;j++){const p=state.photos[page*count+j],x=margin+(land?(j%2)*(cw+gap):0),y=top+(land?Math.floor(j/2):j)*(ch+gap);g.fillStyle='#f7f9fa';g.fillRect(x,y,cw,ch);g.strokeStyle='#c8d4d8';g.lineWidth=1;g.strokeRect(x,y,cw,ch);if(!p)continue;const iw=land?cw:cw*.63,ih=land?ch-108:ch;fitImage(g,p.img,x+1,y+1,iw-2,ih-2);g.fillStyle='#087e79';g.fillRect(x+12,y+12,52,40);g.fillStyle='white';g.font='bold 25px sans-serif';g.textAlign='center';g.fillText(String(page*count+j+1),x+38,y+40);g.textAlign='left';const tx=land?x:x+iw,ty=land?y+ih:y,tw=land?cw:cw-iw,th=land?108:ch;g.fillStyle='white';g.fillRect(tx,ty,tw,th);g.strokeStyle='#c8d4d8';g.beginPath();g.moveTo(tx,ty);g.lineTo(land?tx+tw:tx,land?ty:ty+th);g.stroke();g.fillStyle='#24353a';g.font='22px sans-serif';wrappedText(g,p.comment,tx+15,ty+31,tw-30,30,Math.floor((th-20)/30));}g.font='15px sans-serif';g.fillStyle='#829399';g.fillText('スナップショット',margin,c.height-margin+10);g.textAlign='right';g.fillText(`${page+1} / ${total}`,c.width-margin,c.height-margin+10);result.push(c)}return result}
async function annotatedDrawing(d){const c=document.createElement('canvas');c.width=d.w;c.height=d.h;const g=c.getContext('2d');g.fillStyle='white';g.fillRect(0,0,d.w,d.h);g.drawImage(d.canvas,0,0);const xml=`<svg xmlns="http://www.w3.org/2000/svg" width="${d.w}" height="${d.h}" viewBox="0 0 ${d.w} ${d.h}">${d.annotations.map(a=>svgAnnotation(a,d)).join('')}</svg>`,url=URL.createObjectURL(new Blob([xml],{type:'image/svg+xml'}));try{const im=new Image();im.src=url;await im.decode();g.drawImage(im,0,0)}finally{URL.revokeObjectURL(url)}return c}
async function allPages(){const pages=photoPages().map(canvas=>({canvas,landscape:state.orientation==='landscape',kind:'photo'}));for(const d of state.drawings)pages.push({canvas:await annotatedDrawing(d),landscape:d.w>=d.h,kind:'drawing',drawing:d});return pages}
function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}
function filename(ext){return(meta().title.replace(/[\\/:*?"<>|]/g,'_')||'指示書')+'.'+ext}
$('#pdf-export').onclick=()=>busy('PDFを作成しています…',async()=>{const doc=await PDFLib.PDFDocument.create();for(const {canvas,landscape}of await allPages()){const page=doc.addPage(landscape?[841.89,595.28]:[595.28,841.89]),im=await doc.embedJpg(canvas.toDataURL('image/jpeg',.94)),size=page.getSize(),r=Math.min(size.width/canvas.width,size.height/canvas.height);page.drawImage(im,{x:(size.width-canvas.width*r)/2,y:(size.height-canvas.height*r)/2,width:canvas.width*r,height:canvas.height*r})}download(new Blob([await doc.save()],{type:'application/pdf'}),filename('pdf'));toast('PDFを保存しました。')});
$('#print').onclick=()=>{const win=window.open('','_blank');if(!win){toast('印刷画面を開くため、ポップアップを許可してください。');return}win.document.write('<html lang="ja"><head><title>指示書 印刷</title></head><body>印刷用の指示書を準備しています…</body></html>');busy('印刷を準備しています…',async()=>{const pages=await allPages();win.document.head.innerHTML=`<meta charset="utf-8"><title>${esc(meta().title)}</title><style>@page{margin:0;size:A4 ${state.orientation}}@page landscape{size:A4 landscape;margin:0}@page portrait{size:A4 portrait;margin:0}*{box-sizing:border-box}body{margin:0}.sheet{break-after:page;display:flex;align-items:center;justify-content:center;overflow:hidden}.sheet:last-child{break-after:auto}.landscape{page:landscape;width:297mm;height:210mm}.portrait{page:portrait;width:210mm;height:297mm}.sheet img{max-width:100%;max-height:100%;object-fit:contain}@media screen{body{background:#eee}.sheet{background:white;margin:20px auto;box-shadow:0 2px 12px #0002}}</style>`;win.document.body.replaceChildren();for(const p of pages){const el=win.document.createElement('div');el.className='sheet '+(p.landscape?'landscape':'portrait');const im=win.document.createElement('img');im.src=p.canvas.toDataURL('image/jpeg',.94);el.append(im);win.document.body.append(el);await im.decode()}win.focus();win.print()})};
window.addEventListener('beforeunload',e=>{if(state.photos.length||state.drawings.length){e.preventDefault();e.returnValue=''}});
render();
import {createExcel} from './excel.js';
$('#excel-export').onclick=()=>busy('Excelを作成しています…',async()=>{download(await createExcel({photos:state.photos,drawings:state.drawings,orientation:state.orientation,meta:meta(),annotatedDrawing}),filename('xlsx'));toast('Excelを保存しました。コメントはExcelでも編集できます。')});
