const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main',rel='http://schemas.openxmlformats.org/officeDocument/2006/relationships',pkg='http://schemas.openxmlformats.org/package/2006/relationships',xml=s=>'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'+s;
export async function createExcel({photos,drawings,orientation,meta,annotatedDrawing}){
 const zip=new JSZip(),sheets=[],media=[],land=orientation==='landscape',per=land?4:3;
 const cell=(ref,value,style=0)=>`<c r="${ref}" s="${style}" t="inlineStr"><is><t xml:space="preserve">${esc(value)}</t></is></c>`;
 for(let i=0;i<Math.ceil(photos.length/per);i++){
  const title=meta.title,m=meta,rows=new Map(),merges=['A1:H1','I1:J1','A2:J2'],images=[],rowH=land?14:16,blocks=[];
  const put=(r,c,v,st=0)=>rows.set(r,(rows.get(r)||'')+cell(c+r,v,st));put(1,'A',title,1);put(1,'I',m.date,2);put(2,'A',m.project,2);
  for(let j=0;j<per;j++){
   const p=photos[i*per+j];if(!p)continue;
   const startRow=land?(j<2?4:28):4+j*23;
   const col=land?(j%2===0?0:5):0,photoCols=land?5:6,photoRows=land?17:21;
   const commentRow=land?startRow+18:startRow,commentCol=land?(col===0?'A':'F'):'G',endCol=land?(col===0?'E':'J'):'J',commentEnd=land?startRow+22:startRow+20;
   merges.push(`${commentCol}${commentRow+1}:${endCol}${commentEnd+1}`);
   put(commentRow+1,commentCol,p.comment,3);
   blocks.push({row:commentRow+1,endRow:commentEnd+1,col:land?col:6,endCol:land?col+4:9});
   const cw=land?70:65,w=photoCols*cw,h=photoRows*rowH*96/72,r=Math.min((w-10)/p.w,(h-10)/p.h),iw=p.w*r,ih=p.h*r;
   const canvas=document.createElement('canvas');canvas.width=Math.round(iw*2);canvas.height=Math.round(ih*2);const ctx=canvas.getContext('2d');ctx.drawImage(p.img,0,0,canvas.width,canvas.height);ctx.fillStyle='#087e79';ctx.fillRect(12,12,76,52);ctx.fillStyle='white';ctx.font='bold 34px sans-serif';ctx.textAlign='center';ctx.fillText(String(i*per+j+1),50,51);
   const mediaId=media.length+1;media.push({id:mediaId,data:canvas.toDataURL('image/jpeg',.94).split(',')[1],ext:'jpg'});
   images.push({mediaId,col,row:startRow,x:(w-iw)/2,y:(h-ih)/2,w:iw,h:ih});
  }
  const last=land?53:74;for(let r=1;r<=last;r++){let cells=rows.get(r)||'';if(!cells)cells=cell('A'+r,'');rows.set(r,cells)}
  const sheetRows=[...rows].sort((a,b)=>a[0]-b[0]).map(([r,c])=>`<row r="${r}" ht="${r===1?29:r===2?24:rowH}" customHeight="1">${c}</row>`).join('');
  sheets.push({name:`写真台帳${i+1}`,landscape:land,images,xml:`<worksheet xmlns="${ns}" xmlns:r="${rel}"><sheetPr><pageSetUpPr fitToPage="1"/></sheetPr><dimension ref="A1:J${last}"/><sheetViews><sheetView workbookViewId="0" showGridLines="0"/></sheetViews><sheetFormatPr defaultRowHeight="${rowH}"/><cols><col min="1" max="10" width="${land?9.29:8.57}" customWidth="1"/></cols><sheetData>${sheetRows}</sheetData><mergeCells count="${merges.length}">${merges.map(r=>`<mergeCell ref="${r}"/>`).join('')}</mergeCells><printOptions horizontalCentered="1"/><pageMargins left="0.25" right="0.25" top="0.3" bottom="0.3" header="0.1" footer="0.1"/><pageSetup paperSize="9" orientation="${land?'landscape':'portrait'}" fitToWidth="1" fitToHeight="1"/><headerFooter><oddFooter>&amp;Cスナップショット · ${i+1}</oddFooter></headerFooter><drawing r:id="rId1"/></worksheet>`,last});
 }
 for(let i=0;i<drawings.length;i++){
  const d=drawings[i],c=await annotatedDrawing(d),mediaId=media.length+1;media.push({id:mediaId,data:c.toDataURL('image/jpeg',.96).split(',')[1],ext:'jpg'});
  const landscape=d.w>=d.h,w=landscape?1000:700,h=w*d.h/d.w,rowHeight=15,last=Math.ceil(h/20)+1;
  sheets.push({name:`図面${i+1}`,landscape,last,images:[{mediaId,col:0,row:0,x:0,y:0,w,h}],xml:`<worksheet xmlns="${ns}" xmlns:r="${rel}"><sheetPr><pageSetUpPr fitToPage="1"/></sheetPr><dimension ref="A1:J${last}"/><sheetViews><sheetView workbookViewId="0" showGridLines="0"/></sheetViews><sheetFormatPr defaultRowHeight="${rowHeight}"/><cols><col min="1" max="10" width="${landscape?13.57:9.29}" customWidth="1"/></cols><sheetData>${Array.from({length:last},(_,r)=>`<row r="${r+1}" ht="15" customHeight="1">${cell('A'+(r+1),'')}</row>`).join('')}</sheetData><printOptions horizontalCentered="1"/><pageMargins left="0.2" right="0.2" top="0.2" bottom="0.2" header="0" footer="0"/><pageSetup paperSize="9" orientation="${landscape?'landscape':'portrait'}" fitToWidth="1" fitToHeight="1"/><drawing r:id="rId1"/></worksheet>`});
 }
 zip.file('_rels/.rels',xml(`<Relationships xmlns="${pkg}"><Relationship Id="rId1" Type="${rel}/officeDocument" Target="xl/workbook.xml"/></Relationships>`));
 zip.file('xl/workbook.xml',xml(`<workbook xmlns="${ns}" xmlns:r="${rel}"><bookViews><workbookView/></bookViews><sheets>${sheets.map((s,i)=>`<sheet name="${esc(s.name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets><definedNames>${sheets.map((s,i)=>`<definedName name="_xlnm.Print_Area" localSheetId="${i}">'${s.name}'!$A$1:$J$${s.last}</definedName>`).join('')}</definedNames></workbook>`));
 zip.file('xl/_rels/workbook.xml.rels',xml(`<Relationships xmlns="${pkg}">${sheets.map((s,i)=>`<Relationship Id="rId${i+1}" Type="${rel}/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}<Relationship Id="rId${sheets.length+1}" Type="${rel}/styles" Target="styles.xml"/></Relationships>`));
 zip.file('xl/styles.xml',xml(`<styleSheet xmlns="${ns}"><fonts count="3"><font><sz val="11"/><name val="Yu Gothic"/></font><font><b/><sz val="18"/><name val="Yu Gothic"/></font><font><sz val="10"/><name val="Yu Gothic"/><color rgb="FF536970"/></font></fonts><fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill></fills><borders count="2"><border/><border><left style="thin"><color rgb="FFCAD4D8"/></left><right style="thin"><color rgb="FFCAD4D8"/></right><top style="thin"><color rgb="FFCAD4D8"/></top><bottom style="thin"><color rgb="FFCAD4D8"/></bottom></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="4"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="0" borderId="0" xfId="0" applyFont="1"><alignment vertical="center"/></xf><xf numFmtId="0" fontId="2" fillId="0" borderId="0" xfId="0" applyFont="1"><alignment vertical="center"/></xf><xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0" applyAlignment="1" applyBorder="1"><alignment wrapText="1" vertical="top"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`));
 for(let i=0;i<sheets.length;i++){
  const s=sheets[i],n=i+1;zip.file(`xl/worksheets/sheet${n}.xml`,xml(s.xml));
  zip.file(`xl/worksheets/_rels/sheet${n}.xml.rels`,xml(`<Relationships xmlns="${pkg}"><Relationship Id="rId1" Type="${rel}/drawing" Target="../drawings/drawing${n}.xml"/></Relationships>`));
  zip.file(`xl/drawings/drawing${n}.xml`,xml(`<xdr:wsDr xmlns:xdr="http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="${rel}">${s.images.map((im,j)=>{const em=v=>Math.round(v*9525);return `<xdr:oneCellAnchor><xdr:from><xdr:col>${im.col}</xdr:col><xdr:colOff>${em(im.x)}</xdr:colOff><xdr:row>${im.row}</xdr:row><xdr:rowOff>${em(im.y)}</xdr:rowOff></xdr:from><xdr:ext cx="${em(im.w)}" cy="${em(im.h)}"/><xdr:pic><xdr:nvPicPr><xdr:cNvPr id="${j+1}" name="写真${j+1}"/><xdr:cNvPicPr><a:picLocks noChangeAspect="1"/></xdr:cNvPicPr></xdr:nvPicPr><xdr:blipFill><a:blip r:embed="rId${j+1}"/><a:stretch><a:fillRect/></a:stretch></xdr:blipFill><xdr:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="${em(im.w)}" cy="${em(im.h)}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></xdr:spPr></xdr:pic><xdr:clientData/></xdr:oneCellAnchor>`}).join('')}</xdr:wsDr>`));
  zip.file(`xl/drawings/_rels/drawing${n}.xml.rels`,xml(`<Relationships xmlns="${pkg}">${s.images.map((im,j)=>`<Relationship Id="rId${j+1}" Type="${rel}/image" Target="../media/image${im.mediaId}.jpg"/>`).join('')}</Relationships>`));
 }
 media.forEach(m=>zip.file(`xl/media/image${m.id}.${m.ext}`,m.data,{base64:true}));
 zip.file('[Content_Types].xml',xml(`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="jpg" ContentType="image/jpeg"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${sheets.map((s,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/drawings/drawing${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.drawing+xml"/>`).join('')}</Types>`));
 return zip.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',compression:'DEFLATE'});
}
