import {photoLayout,paperDimensions} from './layout.js';
import {QR_DATA} from './qr.js?v=20261008-rotation-sekokan';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
const ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main',rel='http://schemas.openxmlformats.org/officeDocument/2006/relationships',pkg='http://schemas.openxmlformats.org/package/2006/relationships',xml=s=>'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'+s;
export async function createExcel({photos,drawings,orientation,paperSize="A4",photosPerPage,meta,annotatedDrawing,drawingDocument}){
 const zip=new JSZip(),sheets=[],media=[],land=orientation==='landscape',layout=photoLayout({paperSize,orientation,photosPerPage}),per=layout.count,paperCode=paperDimensions(paperSize,land).excelSize;
 const colName=i=>{let s='';for(i++;i;i=Math.floor((i-1)/26))s=String.fromCharCode(65+(i-1)%26)+s;return s};
 const qrId=1;media.push({id:qrId,data:QR_DATA.split(',')[1],ext:'png'});
 const addFooter=(images,row)=>images.push({mediaId:qrId,col:0,row,x:0,y:0,w:84,h:84});
 const cell=(ref,value,style=0)=>`<c r="${ref}" s="${style}" t="inlineStr"><is><t xml:space="preserve">${esc(value)}</t></is></c>`;
 for(let i=0;i<Math.ceil(photos.length/per);i++){
  const rows=new Map(),merges=['A1:R1','S1:X1','A2:X2'],images=[],rowH=15,columns=24,scale=paperSize==='A3'?Math.SQRT2:1,pageW=(land?1000:700)*scale,pageH=pageW*(land?210/297:297/210),colW=pageW/columns,blockCols=columns/layout.cols,blockRows=Math.max(4,Math.floor((Math.floor((pageH-190)/20)-(layout.rows-1))/layout.rows));
  const put=(r,col,v,st=0)=>rows.set(r,(rows.get(r)||'')+cell(colName(col)+r,v,st));put(1,0,meta.title,1);put(1,18,meta.date,2);put(2,0,meta.project,2);
  for(let j=0;j<per;j++){
   const p=photos[i*per+j],col=(j%layout.cols)*blockCols,startRow=4+Math.floor(j/layout.cols)*(blockRows+1),photoCols=land?blockCols:Math.max(1,Math.floor(blockCols*.63)),photoRows=land?Math.max(1,Math.floor(blockRows*.72)):blockRows;
   const commentRow=land?startRow+photoRows:startRow,commentCol=land?col:col+photoCols,commentEndRow=startRow+blockRows-1,commentEndCol=col+blockCols-1;
   if(!p)continue;
   if(p.blank){const start=colName(col)+(startRow+1),end=colName(commentEndCol)+(commentEndRow+1);if(start!==end)merges.push(start+':'+end);put(startRow+1,col,'',3);continue;}
   const start=colName(commentCol)+(commentRow+1),end=colName(commentEndCol)+(commentEndRow+1);if(start!==end)merges.push(start+':'+end);put(commentRow+1,commentCol,p.comment||'',3);
   const w=photoCols*colW,h=photoRows*20,r=Math.min((w-10)/p.w,(h-10)/p.h),iw=p.w*r,ih=p.h*r;
   const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(iw*2));canvas.height=Math.max(1,Math.round(ih*2));const ctx=canvas.getContext('2d');ctx.drawImage(p.editedCanvas||p.img,0,0,canvas.width,canvas.height);const bw=Math.min(76,canvas.width*.14),bh=bw*.68;ctx.fillStyle='#087ce8';ctx.fillRect(8,8,bw,bh);ctx.fillStyle='white';ctx.font='bold '+(bh*.65)+'px sans-serif';ctx.textAlign='center';ctx.fillText(String(photos.slice(0,i*per+j+1).filter(p=>!p.blank).length),8+bw/2,8+bh*.73);
   const mediaId=media.length+1;media.push({id:mediaId,data:canvas.toDataURL('image/jpeg',.94).split(',')[1],ext:'jpg'});images.push({mediaId,col,row:startRow,x:(w-iw)/2,y:(h-ih)/2,w:iw,h:ih});
  }
  const footerRow=4+layout.rows*(blockRows+1)+2,last=footerRow+6;addFooter(images,footerRow-1);merges.push('D'+(footerRow+1)+':R'+(footerRow+3));put(footerRow+1,3,'セコカンの写真指示ツール',2);
  for(let r=1;r<=last;r++)if(!rows.has(r))rows.set(r,cell('A'+r,''));
  const sheetRows=[...rows].sort((a,b)=>a[0]-b[0]).map(([r,c])=>'<row r="'+r+'" ht="'+(r===1?29:r===2?24:rowH)+'" customHeight="1">'+c+'</row>').join('');
  sheets.push({name:'写真台帳'+(i+1),landscape:land,images,last,lastCol:'X',xml:'<worksheet xmlns="'+ns+'" xmlns:r="'+rel+'"><sheetPr><pageSetUpPr fitToPage="1"/></sheetPr><dimension ref="A1:X'+last+'"/><sheetViews><sheetView workbookViewId="0" showGridLines="0"/></sheetViews><sheetFormatPr defaultRowHeight="'+rowH+'"/><cols><col min="1" max="24" width="'+((colW-5)/7).toFixed(3)+'" customWidth="1"/></cols><sheetData>'+sheetRows+'</sheetData><mergeCells count="'+merges.length+'">'+merges.map(r=>'<mergeCell ref="'+r+'"/>').join('')+'</mergeCells><printOptions horizontalCentered="1"/><pageMargins left="0.25" right="0.25" top="0.3" bottom="0.3" header="0.1" footer="0.1"/><pageSetup paperSize="'+paperCode+'" orientation="'+(land?'landscape':'portrait')+'" fitToWidth="1" fitToHeight="1"/><headerFooter><oddFooter>&amp;R'+esc(meta.date)+' · '+(i+1)+'</oddFooter></headerFooter><drawing r:id="rId1"/></worksheet>'});
 }
 // Build editable, paginated comment lists; blank comments are omitted.
 const entries=photos.filter(p=>!p.blank).map((p,i)=>({number:i+1,comment:p.comment})).filter(e=>e.comment.trim()),groups=[];let group=[],used=0;const budget=land?460:700;
 for(const e of entries){const lines=[];for(const line of e.comment.split('\n')){const chars=Array.from(line);if(!chars.length)lines.push('');for(let at=0;at<chars.length;at+=42)lines.push(chars.slice(at,at+42).join(''))}const perChunk=Math.floor((budget-20)/16);for(let at=0;at<lines.length;at+=perChunk){const part=lines.slice(at,at+perChunk),height=Math.max(32,part.length*16+12);if(group.length&&used+height>budget){groups.push(group);group=[];used=0}group.push({number:e.number,comment:part.join('\n'),height,continued:at>0});used+=height}}
 if(group.length)groups.push(group);
 for(let i=0;i<groups.length;i++){const images=[],merges=['A1:H1','I1:J1','A2:J2','A4:B4','C4:J4'];let rows=`<row r="1" ht="29" customHeight="1">${cell('A1',meta.title+' / コメント一覧',1)}${cell('I1',meta.date,2)}</row><row r="2" ht="24" customHeight="1">${cell('A2',meta.project,2)}</row><row r="4" ht="26" customHeight="1">${cell('A4','写真番号',1)}${cell('C4','コメント・指示内容',1)}</row>`,row=5;
 for(const e of groups[i]){merges.push(`A${row}:B${row}`,`C${row}:J${row}`);rows+=`<row r="${row}" ht="${e.height}" customHeight="1">${cell('A'+row,e.number+(e.continued?'（続）':''),3)}${cell('C'+row,e.comment,3)}</row>`;row++}row+=2;addFooter(images,row-1);merges.push(`C${row+1}:H${row+3}`);rows+=`<row r="${row+1}" ht="14" customHeight="1">${cell('C'+(row+1),'セコカンの写真指示ツール',2)}</row>`;const last=row+6;for(let j=row+2;j<=last;j++)rows+=`<row r="${j}" ht="14" customHeight="1">${cell('A'+j,'')}</row>`;
 sheets.push({name:`コメント一覧${i+1}`,landscape:land,last,images,xml:`<worksheet xmlns="${ns}" xmlns:r="${rel}"><sheetPr><pageSetUpPr fitToPage="1"/></sheetPr><dimension ref="A1:J${last}"/><sheetViews><sheetView workbookViewId="0" showGridLines="0"/></sheetViews><sheetFormatPr defaultRowHeight="14"/><cols><col min="1" max="10" width="9.29" customWidth="1"/></cols><sheetData>${rows}</sheetData><mergeCells count="${merges.length}">${merges.map(r=>`<mergeCell ref="${r}"/>`).join('')}</mergeCells><printOptions horizontalCentered="1"/><pageMargins left="0.25" right="0.25" top="0.3" bottom="0.3" header="0.1" footer="0.1"/><pageSetup paperSize="${paperCode}" orientation="${land?'landscape':'portrait'}" fitToWidth="1" fitToHeight="1"/><headerFooter><oddFooter>&amp;R${esc(meta.date)} · コメント一覧 ${i+1}</oddFooter></headerFooter><drawing r:id="rId1"/></worksheet>`});}
 for(let i=0;i<drawings.length;i++){
  const d=drawings[i],c=drawingDocument?await drawingDocument(d):await annotatedDrawing(d),mediaId=media.length+1;media.push({id:mediaId,data:c.toDataURL('image/jpeg',.96).split(',')[1],ext:'jpg'});
  const landscape=d.w>=d.h,w=landscape?1000:700,h=w*c.height/c.width,rowHeight=15,last=Math.ceil(h/20)+1;
  sheets.push({name:`図面${i+1}`,landscape,last,images:[{mediaId,col:0,row:0,x:0,y:0,w,h}],xml:`<worksheet xmlns="${ns}" xmlns:r="${rel}"><sheetPr><pageSetUpPr fitToPage="1"/></sheetPr><dimension ref="A1:J${last}"/><sheetViews><sheetView workbookViewId="0" showGridLines="0"/></sheetViews><sheetFormatPr defaultRowHeight="${rowHeight}"/><cols><col min="1" max="10" width="${landscape?13.57:9.29}" customWidth="1"/></cols><sheetData>${Array.from({length:last},(_,r)=>`<row r="${r+1}" ht="15" customHeight="1">${cell('A'+(r+1),'')}</row>`).join('')}</sheetData><printOptions horizontalCentered="1"/><pageMargins left="0.2" right="0.2" top="0.2" bottom="0.2" header="0" footer="0"/><pageSetup paperSize="${paperCode}" orientation="${landscape?'landscape':'portrait'}" fitToWidth="1" fitToHeight="1"/><drawing r:id="rId1"/></worksheet>`});
 }
 zip.file('_rels/.rels',xml(`<Relationships xmlns="${pkg}"><Relationship Id="rId1" Type="${rel}/officeDocument" Target="xl/workbook.xml"/></Relationships>`));
 zip.file('xl/workbook.xml',xml(`<workbook xmlns="${ns}" xmlns:r="${rel}"><bookViews><workbookView/></bookViews><sheets>${sheets.map((s,i)=>`<sheet name="${esc(s.name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets><definedNames>${sheets.map((s,i)=>`<definedName name="_xlnm.Print_Area" localSheetId="${i}">'${s.name}'!$A$1:$${s.lastCol||'J'}$${s.last}</definedName>`).join('')}</definedNames></workbook>`));
 zip.file('xl/_rels/workbook.xml.rels',xml(`<Relationships xmlns="${pkg}">${sheets.map((s,i)=>`<Relationship Id="rId${i+1}" Type="${rel}/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}<Relationship Id="rId${sheets.length+1}" Type="${rel}/styles" Target="styles.xml"/></Relationships>`));
 zip.file('xl/styles.xml',xml(`<styleSheet xmlns="${ns}"><fonts count="3"><font><sz val="11"/><name val="Yu Gothic"/></font><font><b/><sz val="18"/><name val="Yu Gothic"/></font><font><sz val="10"/><name val="Yu Gothic"/><color rgb="FF536970"/></font></fonts><fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill></fills><borders count="2"><border/><border><left style="thin"><color rgb="FFCAD4D8"/></left><right style="thin"><color rgb="FFCAD4D8"/></right><top style="thin"><color rgb="FFCAD4D8"/></top><bottom style="thin"><color rgb="FFCAD4D8"/></bottom></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="4"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="0" borderId="0" xfId="0" applyFont="1"><alignment vertical="center"/></xf><xf numFmtId="0" fontId="2" fillId="0" borderId="0" xfId="0" applyFont="1"><alignment vertical="center"/></xf><xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0" applyAlignment="1" applyBorder="1"><alignment wrapText="1" vertical="top"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`));
 for(let i=0;i<sheets.length;i++){
  const s=sheets[i],n=i+1;zip.file(`xl/worksheets/sheet${n}.xml`,xml(s.xml));
  zip.file(`xl/worksheets/_rels/sheet${n}.xml.rels`,xml(`<Relationships xmlns="${pkg}"><Relationship Id="rId1" Type="${rel}/drawing" Target="../drawings/drawing${n}.xml"/></Relationships>`));
  zip.file(`xl/drawings/drawing${n}.xml`,xml(`<xdr:wsDr xmlns:xdr="http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="${rel}">${s.images.map((im,j)=>{const em=v=>Math.round(v*9525);return `<xdr:oneCellAnchor><xdr:from><xdr:col>${im.col}</xdr:col><xdr:colOff>${em(im.x)}</xdr:colOff><xdr:row>${im.row}</xdr:row><xdr:rowOff>${em(im.y)}</xdr:rowOff></xdr:from><xdr:ext cx="${em(im.w)}" cy="${em(im.h)}"/><xdr:pic><xdr:nvPicPr><xdr:cNvPr id="${j+1}" name="写真${j+1}"/><xdr:cNvPicPr><a:picLocks noChangeAspect="1"/></xdr:cNvPicPr></xdr:nvPicPr><xdr:blipFill><a:blip r:embed="rId${j+1}"/><a:stretch><a:fillRect/></a:stretch></xdr:blipFill><xdr:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="${em(im.w)}" cy="${em(im.h)}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></xdr:spPr></xdr:pic><xdr:clientData/></xdr:oneCellAnchor>`}).join('')}</xdr:wsDr>`));
  zip.file(`xl/drawings/_rels/drawing${n}.xml.rels`,xml(`<Relationships xmlns="${pkg}">${s.images.map((im,j)=>`<Relationship Id="rId${j+1}" Type="${rel}/image" Target="../media/image${im.mediaId}.${media[im.mediaId-1].ext}"/>`).join('')}</Relationships>`));
 }
 media.forEach(m=>zip.file(`xl/media/image${m.id}.${m.ext}`,m.data,{base64:true}));
 zip.file('[Content_Types].xml',xml(`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="jpg" ContentType="image/jpeg"/><Default Extension="png" ContentType="image/png"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${sheets.map((s,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/drawings/drawing${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.drawing+xml"/>`).join('')}</Types>`));
 return zip.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',compression:'DEFLATE'});
}
