import {setupColorPalette} from './color-palette.js';
// Keep editable vectors separate from the original photo and cache only the output.
export function setupPhotoEditor({getPhoto,render,svgAnnotation,rotateAnnotation,uid,toast}) {
  const dialog=document.createElement('dialog');dialog.className='photo-editor';
  dialog.innerHTML=`<div class="photo-editor-head"><strong id="photo-editor-title">写真を編集</strong><button id="photo-cancel">キャンセル</button><button id="photo-save" class="primary">完成・反映</button></div><div class="photo-editor-tools"><label>色 <input id="photo-color" type="color" value="#e44838"></label><label>線幅 <select id="photo-stroke"><option value="3">細</option><option value="6" selected>中</option><option value="12">太</option></select></label>${[['select','選択・移動'],['line','線'],['circle','丸'],['rect','四角'],['marker','マーカー'],['pen','フリーハンド'],['text','文字'],['number','番号']].map(([t,l])=>`<button data-photo-tool="${t}">${l}</button>`).join('')}<button id="photo-rotate-left" title="写真を左に90度回転">↶ 左90°</button><button id="photo-rotate-right" title="写真を右に90度回転">↷ 右90°</button><button id="photo-undo">戻す</button><button id="photo-redo">やり直す</button><button id="photo-delete">選択を削除</button></div><div class="photo-editor-options"><label id="photo-line-label">線の種類 <select id="photo-line-style"><option value="plain">実線</option><option value="arrow" selected>矢印</option><option value="double-arrow">両矢印</option><option value="dots">両端●</option><option value="dashed">点線</option><option value="dashed-arrow">点線矢印</option></select></label><label id="photo-text-label" hidden>文字 <input id="photo-text" maxlength="200" placeholder="配置する文字を入力"></label><label id="photo-number-label" hidden>番号 <input id="photo-number" type="number" min="1" max="9999" value="1"></label><span id="photo-hint">写真上をドラッグして矢印を描きます。</span></div><div class="photo-editor-viewport"><div class="photo-editor-stage"><img alt="編集する元写真"><svg xmlns="http://www.w3.org/2000/svg" aria-label="写真編集エリア"></svg></div></div><p class="photo-editor-note">元写真はそのまま残ります。完成後も「編集」から書き込みを変更できます。</p>`;
  dialog.setAttribute('aria-labelledby','photo-editor-title');document.body.append(dialog);
  const $=s=>dialog.querySelector(s),svg=$('svg'),stage=$('.photo-editor-stage');
  setupColorPalette($('#photo-color'));
  let photo,targetPhoto,baseImage,baseW,baseH,rotation=0,items=[],history=[],hi=0,selected=null,tool='line',pointer=null,preview=null,saving=false;
  const hints={select:'書き込みを選んでドラッグすると移動できます。色・線幅の変更や削除もできます。',line:'線の種類を選び、写真上をドラッグして描きます。',circle:'写真上をドラッグして丸で囲みます。',rect:'写真上をドラッグして四角で囲みます。',marker:'写真上をドラッグして色を付けます。',pen:'写真上をドラッグして自由に線を描きます。',text:'文字を入力して写真上をクリックします。',number:'番号を入力して写真上をクリックします。'};
  function paint(){svg.innerHTML=items.concat(preview?[preview]:[]).map(a=>svgAnnotation(a,photo,a.id===selected)).join('');$('#photo-undo').disabled=hi===0;$('#photo-redo').disabled=hi===history.length-1;$('#photo-delete').disabled=!selected}
  function record(){history=history.slice(0,hi+1);history.push({items:structuredClone(items),rotation});if(history.length>100)history.shift();hi=history.length-1;paint()}
  function choose(t){tool=t;selected=null;dialog.querySelectorAll('[data-photo-tool]').forEach(b=>b.classList.toggle('active',b.dataset.photoTool===t));$('#photo-line-label').hidden=t!=='line';$('#photo-text-label').hidden=t!=='text';$('#photo-number-label').hidden=t!=='number';$('#photo-hint').textContent=hints[t];paint()}
  function finishGesture(cancel=false){if(!pointer&&!preview)return;if(cancel&&pointer?.original){items[items.findIndex(a=>a.id===pointer.original.id)]=pointer.original}else if(!cancel){if(preview&&(preview.points?.length>1||Math.hypot(preview.x2-preview.x,preview.y2-preview.y)>3))items.push(preview);if(preview||pointer?.changed)record()}pointer=null;preview=null;paint()}
  function undo(dir){finishGesture();if(hi+dir<0||hi+dir>=history.length)return;hi+=dir;items=structuredClone(history[hi].items);rotation=history[hi].rotation;selected=null;refreshPhoto();paint()}
  function refreshPhoto(){const c=document.createElement('canvas'),turn=rotation%2;c.width=turn?baseH:baseW;c.height=turn?baseW:baseH;const g=c.getContext('2d');g.translate(c.width/2,c.height/2);g.rotate(rotation*Math.PI/2);g.drawImage(baseImage,-baseW/2,-baseH/2);photo.w=c.width;photo.h=c.height;photo.img=c;$('img').src=rotation?c.toDataURL('image/jpeg',.94):targetPhoto.src;stage.style.aspectRatio=photo.w+'/'+photo.h;stage.style.width='min(100%, '+Math.round(65*photo.w/photo.h)+'vh)';svg.setAttribute('viewBox',`0 0 ${photo.w} ${photo.h}`)}
  function rotate(clockwise){if(saving)return;finishGesture();items=items.map(a=>rotateAnnotation(a,photo.w,photo.h,clockwise));rotation=(rotation+(clockwise?1:3))%4;selected=null;refreshPhoto();record()}
  $('#photo-rotate-left').onclick=()=>rotate(false);$('#photo-rotate-right').onclick=()=>rotate(true);
  function point(e){const r=svg.getBoundingClientRect();return{x:Math.max(0,Math.min(photo.w,(e.clientX-r.left)*photo.w/r.width)),y:Math.max(0,Math.min(photo.h,(e.clientY-r.top)*photo.h/r.height))}}
  svg.onpointerdown=e=>{if(e.button!==0||saving||pointer)return;e.preventDefault();svg.setPointerCapture(e.pointerId);const p=point(e);if(tool==='select'){selected=e.target.closest('[data-id]')?.dataset.id||null;const a=items.find(a=>a.id===selected);pointer=a?{start:p,original:structuredClone(a),changed:false}:null;if(a){$('#photo-color').value=a.color;$('#photo-stroke').value=a.stroke;if(a.type==='text')$('#photo-text').value=a.text}paint();return}const a={id:uid(),type:tool,...p,color:$('#photo-color').value,stroke:Number($('#photo-stroke').value),lineStyle:$('#photo-line-style').value};if(tool==='text'){a.text=$('#photo-text').value.trim();if(!a.text){toast('配置する文字を入力してください。');return}}if(tool==='number'){a.number=Math.floor(Number($('#photo-number').value));if(!Number.isFinite(a.number)||a.number<1||a.number>9999){toast('番号は1〜9999で入力してください。');return}}if(tool==='text'||tool==='number'){items.push(a);record();return}a.x2=p.x;a.y2=p.y;if(tool==='marker'||tool==='pen')a.points=[[p.x,p.y]];preview=a;pointer={start:p};paint()};
  svg.onpointermove=e=>{if(!pointer)return;const p=point(e);if(pointer.original){const o=pointer.original,dx=p.x-pointer.start.x,dy=p.y-pointer.start.y,a=items.find(a=>a.id===o.id);a.x=o.x+dx;a.y=o.y+dy;if(o.x2!==undefined){a.x2=o.x2+dx;a.y2=o.y2+dy}if(o.points)a.points=o.points.map(([x,y])=>[x+dx,y+dy]);pointer.changed=dx!==0||dy!==0}else if(preview){preview.x2=p.x;preview.y2=p.y;if(preview.points)preview.points.push([p.x,p.y])}paint()};
  svg.onpointerup=()=>finishGesture();svg.onpointercancel=()=>finishGesture(true);
  dialog.querySelectorAll('[data-photo-tool]').forEach(b=>b.onclick=()=>{finishGesture();choose(b.dataset.photoTool)});
  $('#photo-undo').onclick=()=>undo(-1);$('#photo-redo').onclick=()=>undo(1);
  $('#photo-delete').onclick=()=>{items=items.filter(a=>a.id!==selected);selected=null;record()};
  ['color','stroke'].forEach(key=>$('#photo-'+key).onchange=e=>{const a=items.find(a=>a.id===selected);if(a){a[key]=key==='stroke'?Number(e.target.value):e.target.value;record()}});
  function close(){if(saving)return;finishGesture(true);dialog.close()}
  $('#photo-cancel').onclick=close;dialog.oncancel=e=>{e.preventDefault();close()};
  dialog.addEventListener('keydown',e=>{e.stopPropagation();if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo(e.shiftKey?1:-1)}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();if(selected)$('#photo-delete').click()}});
  $('#photo-save').onclick=async()=>{if(saving)return;finishGesture();saving=true;$('#photo-save').disabled=true;try{const c=document.createElement('canvas');c.width=photo.w;c.height=photo.h;const g=c.getContext('2d');g.drawImage(photo.img,0,0);if(items.length){const xml=`<svg xmlns="http://www.w3.org/2000/svg" width="${photo.w}" height="${photo.h}" viewBox="0 0 ${photo.w} ${photo.h}">${items.map(a=>svgAnnotation(a,photo)).join('')}</svg>`,url=URL.createObjectURL(new Blob([xml],{type:'image/svg+xml'}));try{const im=new Image();im.src=url;await im.decode();g.drawImage(im,0,0)}finally{URL.revokeObjectURL(url)}}targetPhoto.originalImage=baseImage;targetPhoto.originalWidth=baseW;targetPhoto.originalHeight=baseH;targetPhoto.rotation=rotation;targetPhoto.w=photo.w;targetPhoto.h=photo.h;targetPhoto.annotations=structuredClone(items);targetPhoto.editedCanvas=items.length||rotation?c:null;targetPhoto.editedSrc=items.length||rotation?c.toDataURL('image/jpeg',.94):null;dialog.close();render();toast('写真の書き込みを反映しました。印刷・PDF・Excelにも反映されます。')}catch(e){console.error(e);toast('反映できませんでした。もう一度お試しください。')}finally{saving=false;$('#photo-save').disabled=false}};
  return id=>{targetPhoto=getPhoto(id);if(!targetPhoto||targetPhoto.blank)return;photo={...targetPhoto};baseImage=targetPhoto.originalImage||targetPhoto.img;baseW=targetPhoto.originalWidth||targetPhoto.w;baseH=targetPhoto.originalHeight||targetPhoto.h;rotation=targetPhoto.rotation||0;items=structuredClone(targetPhoto.annotations||[]);history=[{items:structuredClone(items),rotation}];hi=0;pointer=null;preview=null;selected=null;$('#photo-editor-title').textContent='写真を編集 · '+photo.name;refreshPhoto();choose('line');dialog.showModal()};
}
